[package]
name = "aoc22"
version = "0.1.0"
authors = ["Hugo Kapp <hugo.kapp@oracle.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
regex = "1"
rayon = "1.6.1"
multimap = "0.8.3"
